services:
  bot:
    build:
      context: .
    container_name: modmail-develop
    restart: always
    ports:
      - 8555:8000
    volumes:
      # Add your volume mount for local plugins here
      - ../modmail-plugins/:/home/modmail/plugins/@local/
    env_file:
      - .dev.env
    environment:
      - CONNECTION_URI=mongodb://db
      - PUID=1000
      - PGID=1000
    depends_on:
      - db

  db:
    image: mongo
    container_name: modmail-devdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./env/devdb:/data/db
    environment:
      - PUID=1000
      - PGID=1000
