services:
  bot:
    image: ghcr.io/raidensakura/modmail:stable
    container_name: modmail
    restart: always
    environment:
      - CONNECTION_URI=mongodb://db
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo
    container_name: modmail-db
    restart: always
    volumes:
      - ./env/db:/data/db
