services:
  bot:
    image: ghcr.io/raidensakura/modmail:stable
    container_name: modmail
    restart: always
    environment:
      - CONNECTION_URI=mongodb://mongo
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
