version: "3.7"
services:
  bot:
    image: ghcr.io/raidensakura/modmail:stable
    container_name: modmail
    restart: always
    env_file:
      - .env
    environment:
      - CONNECTION_URI=mongodb://mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
