name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: "bug"
body:
  - type: input
    id: bot-info-version
    attributes:
      label: Bot Version
      description: Check it with `@modmail about`
      placeholder: eg. v4.2.0
    validations:
      required: true
  - type: dropdown
    id: bot-info-hosting
    attributes:
      label: How are you hosting Modmail?
      description: You can check it with `@modmail about` if you are unsure
      options:
        - Local-hosting
        - Docker
        - Other
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Error Logs / Screenshot
      placeholder: https://hastebin.cc/paste-id
      description:
        "If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.
        
        If your Modmail bot is not online or the previous command did not generate a link, restart your bot and verify the issue is reproducible.
        After that, upload a screenshot of the **full** error into [postimages](https://postimages.org/) or any equivalent website, or
        copy and paste **entire** error stack trace into the additional field below."
  - type: textarea
    id: screenshots
    attributes:
      label: Brief Description
      description: "Provide a short description of the issue you're facing."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "You may provide additional context or stack trace for us to better understand how this issue occured."
