name: Feature Request
description: Suggest an idea for this project
title: "[FR]: "
labels: "enhancement"
body:
  - type: textarea
    id: problem-relation
    attributes:
      label: Feature Request.
      description: A short, clear and concise description of what the suggestion is.
      placeholder: eg. I would like Modmail to have...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Feature Description.
      description: A detailed, clear and concise description of how the suggested feature would improve Modmail or solve problems the users are facing.
    validations:
      required: true
  - type: checkboxes
    id: complications
    attributes:
      label: Which application is the feature intended for?
      options:
        - label: Modmail
        - label: Logviewer
