name: Lint python

on:
  push:
    branches:
      - stable
      - develop
  pull_request:

jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    name: Python ${{ matrix.python-version }} on ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3.0.0
    - name: Install dependencies
      run: |
        poetry install --no-root --only dev
    - name: Ruff
      run: poetry run ruff . --no-fix --config pyproject.toml
      continue-on-error: true
    - name: Black
      run: |
        poetry run black . --diff --check --config pyproject.toml
