name: Lint python

on:
  push:
    branches:
      - stable
      - develop
  pull_request:

jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    name: Python ${{ matrix.python-version }} on ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install black ruff
    - name: Ruff
      run: ruff . --no-fix
      continue-on-error: true
    - name: Black
      run: |
        black . --diff --check
