name: Load test

on:
  push:
    branches:
      - stable
      - develop

jobs:
  load-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    name: Load Modmail - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
      - name: Cache poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Run script loadcheck.py
        run: |
          pipenv run python .github/workflows/scripts/loadcheck.py
        env:
          TOKEN: ${{ secrets.DISCORD_TEST_BOT }}
          CONNECTION_URI: ${{ secrets.CONNECTION_URI }}
          LOG_URL: https://domain.example
          GUILD_ID: "616969119685935162"
          OWNERS: "243316261264556032,505386507440488458"
          DATA_COLLECTION: off
          LOG_LEVEL: DEBUG

      - name: Save Modmail output as Artifact
        if: always() # still run if prev step failed
        uses: actions/upload-artifact@v4
        with:
          name: "Modmail log - Python ${{ matrix.python-version }}"
          path: modmail.log
